Projekt/project/routes/web.php
<?php

use App\Models\Donation;
use App\Models\Fundraiser;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|s
*/

Route::get('/', function () {
    $best_3_users = array_slice(User::scopeRanking(Donation::all()), 0, 3);
    $latest_3_donations = Donation::all()->sortByDesc('created_at')->take(3);
    return view('Toss_a_coin', ['latest_3_donations' => $latest_3_donations, 'best_3_users' => $best_3_users])
        ->withFundraisers(Fundraiser::orderByDesc('created_at')->get()->take(3))
        ->withDonations(Donation::all());
})->name('home');

Route::get('/dashboard', function () {
    $user_donations = Donation::all()->where('user_id', '=', auth()->user()->id)->where('is_anonymous', '=', '0');
    $user_anonymous_donations = Donation::all()->where('user_id', '=', auth()->user()->id)->where('is_anonymous', '=', '1');
    $user_fundraisers = Fundraiser::all()->where('user_id', '=', auth()->user()->id);
    $sum_donations = Donation::all()->where('user_id', '=', auth()->user()->id)->sum('amount');

    return view('dashboard', ["user_donations" => $user_donations, "user_fundraisers" => $user_fundraisers,
        "user_anonymous_donations" =>$user_anonymous_donations, "sum_donations" => $sum_donations])
        ->withFundraisers(Fundraiser::all())
        ->withDonations(Donation::all());
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('fundraisers', \App\Http\Controllers\FundraiserController::class);
Route::resource('fundraisers.donations', \App\Http\Controllers\FundraiserDonationController::class);
Route::resource('users', \App\Http\Controllers\Auth\RegisteredUserController::class);

Projekt/project/app/Models/Fundraiser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Fundraiser extends Model
{
    use HasFactory;

    public function category(){
        return $this->belongsTo(Category::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function donations(){
        return $this->hasMany(Donation::class);
    }
}

Projekt/project/app/Http/Controllers/FundraiserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Fundraiser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use \App\Models\Donation;

class FundraiserController extends Controller
{
    public function __construct() {
        $this->middleware('verified')->only('create', 'edit');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $this->validate($request, [
            'amount_to_be_raised' => 'numeric|nullable|min:0|max:99999999'
        ]);

        $fundraisers = Fundraiser::select("*")->orderByDesc('created_at');

        if($request->input('filter') == 'all' ){
            session(['amount_to_be_raised' => $request->input('amount_to_be_raised')]);
            session(['category' => $request->input('category')]);
            session(['stop_date' => $request->input('stop_date')]);
            session(['start_date' => $request->input('start_date')]);
            $paged = $fundraisers->paginate(10);
            return view('fundraisers.index', ["paged" => $paged])->withFundraisers($fundraisers->get())->withCategories(Category::all());
        }
        if($request->has('amount_to_be_raised') ){
            session(['amount_to_be_raised' => $request->input('amount_to_be_raised')]);
            session(['category' => $request->input('category')]);
            session(['stop_date' => $request->input('stop_date')]);
            session(['start_date' => $request->input('start_date')]);
        }

        if(isset($_GET['submit'])) {
            $fundraisers = Fundraiser::select("*");
            $fundraisers = $this->sort($fundraisers);
        }
        else {
            $fundraisers = $this->filter($fundraisers);
        }

        $paged = $fundraisers->paginate(10);

        return view('fundraisers.index', ["paged" => $paged])->withFundraisers($fundraisers->get())->withCategories(Category::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('fundraisers.create')->withCategories(Category::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'category' => 'required',
            'description' => 'required',
            'stop_date' => 'required|date|after:now',
            'amount_to_be_raised' => 'required|gt:0'
        ]);

        $fundraiser = new Fundraiser();
        $fundraiser->title = $request->title;
        $fundraiser->category_id = Category::where('name', $request->category)->firstOrFail()->id;
        $fundraiser->description = $request->description;
        $fundraiser->stop_date = $request->stop_date . " 23:59:59";
        $fundraiser->amount_raised = 0;
        $fundraiser->amount_to_be_raised = $request->amount_to_be_raised;
        $fundraiser->user_id = Auth::id();

        $fundraiser->save();

        return redirect()->route('fundraisers.show', $fundraiser);
    }

    /**
     * Display the specified resource.
     *
     * @param  Fundraiser $fundraiser
     * @return \Illuminate\Http\Response
     */
    public function show(Fundraiser $fundraiser)
    {   $latest_5_donations = Donation::orderBy('created_at')->where('fundraiser_id', $fundraiser->id)->get()->take(5);
        $is_closed = $fundraiser->stop_date < \Carbon\Carbon::now()->toDateTimeString();
        return view('fundraisers.show', ["latest_5_donations" => $latest_5_donations, 'is_closed' => $is_closed])->withFundraiser($fundraiser);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Fundraiser $fundraiser
     * @return \Illuminate\Http\Response
     */
    public function edit(Fundraiser $fundraiser)
    {
        $is_owner = auth::id() == $fundraiser->user->id;
        $is_closed = $fundraiser->stop_date < \Carbon\Carbon::now()->toDateTimeString();
        if ($is_owner and !$is_closed) {
            return view("fundraisers.edit")->withFundraiser($fundraiser)->withCategories(Category::all());
        } else {
            abort(403);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Fundraiser $fundraiser
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Fundraiser $fundraiser)
    {

        $this->validate($request, [
            'title' => 'required',
            'category' => 'required',
            'description' => 'required',
            'stop_date' => 'required|date|after:now',
            'amount_to_be_raised' => 'required|gt:0'
        ]);

        $fundraiser->title = $request->title;
        $fundraiser->category_id = Category::where('name', $request->category)->firstOrFail()->id;
        $fundraiser->description = $request->description;
        $fundraiser->stop_date = $request->stop_date . " 23:59:59";
        $fundraiser->amount_to_be_raised = $request->amount_to_be_raised;
        $fundraiser->updated_at = \Carbon\Carbon::now()->toDateTimeString();

        $fundraiser->save();

        return redirect()->route('fundraisers.show', $fundraiser);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Fundraiser $fundraiser
     * @return \Illuminate\Http\Response
     */
    public function destroy(Fundraiser $fundraiser)
    {
        if(auth::id() != $fundraiser->user->id) {
            abort(403);
        }

        $fundraiser->delete();

        return redirect()->route('fundraisers.index');
    }

    public function filter($fundraisers){
        $fundraisers = $fundraisers->where('amount_to_be_raised','>=',(float)session('amount_to_be_raised'));

        if( session('category') != null) {
            $id = Category::where('name', session('category'))->firstOrFail()->id;
            $fundraisers = $fundraisers->where('category_id', '=', $id);
        }

        if( session('stop_date') != '' )
            $fundraisers = $fundraisers->where('stop_date','<=',session('stop_date'));
        if( session('start_date') != '' )
            $fundraisers = $fundraisers->where('created_at','<=',session('start_date'));

        return $fundraisers;
    }

    public function sort($fundraisers){
        if($_GET['submit'] == 'amount')
              return $this->filter($fundraisers)->orderBy('amount_to_be_raised', 'DESC');
        if($_GET['submit'] == 'date1')
            return $this->filter($fundraisers)->orderBy('stop_date', 'ASC');
        if($_GET['submit'] == 'amount2')
            return $this->filter($fundraisers)->orderBy('amount_to_be_raised', 'ASC');
        if($_GET['submit'] == 'date2')
            return $this->filter($fundraisers)->orderBy('stop_date', 'DESC');
        return  $this->filter($fundraisers);
    }
}

Projekt/project/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

Projekt/project/resources/views/fundraisers/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Creating a fundraiser') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form id="create_form"  method="post" action="{{ route('fundraisers.store') }}">

                        @csrf

                        <div class="mt-4">
                            <x-label for="title" :value="__('Title')" />
                            <x-input id="title" class="block mt-1 w-full" type="text" name="title" :value="old('title')" />
                        </div>

                        <div class="mt-4">
                            <x-label for="category" :value="__('Category')" />
                            <select id="category" class="block mt-1 w-full" name="category">
                                <option value="" selected disabled hidden>-- Choose category --</option>
                                @foreach($categories as $category)
                                    <option
                                        @if($category->name == old('category'))
                                            selected
                                        @endif
                                        value="{{ $category->name }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="mt-4">
                            <x-label for="description" :value="__('Description')" />
                            <x-input id="description" class="block mt-1 w-full" type="text" name="description" :value="old('description')" />
                        </div>

                        <div class="mt-4">
                            <x-label for="stop_date" :value="__('Stop date')" />
                            <x-input id="stop_date" class="block mt-1 w-full" type="date" name="stop_date" :value="old('stop_date')" />
                        </div>

                        <div class="mt-4">
                            <x-label for="amount_to_be_raised" :value="__('Amount to be raised')" />
                            <x-input id="amount_to_be_raised" class="block mt-1 w-full" type="number" name="amount_to_be_raised"
                                     :value="old('amount_to_be_raised')" />
                        </div>



                        <div class="flex items-center justify-end mt-4">

                            <x-button class="ml-4">
                                {{ __('Create') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

Projekt/project/resources/views/fundraisers/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Editing a fundraiser') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <x-auth-validation-errors class="mb-4" :errors="$errors" />
                    <form method="post" action="{{ route('fundraisers.update', $fundraiser) }}">

                        @csrf
                        @method("PUT")

                        <div class="mt-4">
                            <x-label for="title" :value="__('Title')" />
                            <x-input id="title" class="block mt-1 w-full" type="text" name="title"
                                     :value="$fundraiser->title" />
                        </div>

                        <div class="mt-4">
                            <x-label for="category" :value="__('Category')" />
                            <select id="category" class="block mt-1 w-full" name="category">
                                <option value="" disabled hidden>-- Choose category --</option>
                                @foreach($categories as $category)
                                    <option
                                        @if($fundraiser->category->name == $category->name)
                                            selected
                                        @endif
                                        >{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="mt-4">
                            <x-label for="description" :value="__('Description')" />
                            <x-input id="description" class="block mt-1 w-full" type="text" name="description"
                                     :value="$fundraiser->description" />
                        </div>

                        <div class="mt-4">
                            <x-label for="stop_date" :value="__('Stop date')" />
                            <x-input id="stop_date" class="block mt-1 w-full" type="date" name="stop_date" :
                                     value="{{$date = \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $fundraiser->stop_date)->format('Y-m-d')}}" />
                        </div>

                        <div class="mt-4">
                            <x-label for="amount_to_be_raised" :value="__('Amount to be raised')" />
                            <x-input id="amount_to_be_raised" class="block mt-1 w-full" type="number" name="amount_to_be_raised"
                                     :value="$fundraiser->amount_to_be_raised" />
                        </div>

                        <div class="flex items-center justify-end mt-4">

                            <x-button class="ml-4">
                                {{ __('Update') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

Projekt/project/resources/views/fundraisers/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('All fundraisers') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <h3  class="font-semibold text-xl text-gray-800 leading-tight">
                        {{ __('Filtration Catalog') }}
                    </h3>
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form id="create_form"  method="get" action="{{ route('fundraisers.index') }}">
                        @csrf
                        <div class="mt-4">
                            <x-label for="category" :value="__('Category')" />
                            <select id="category" class="block mt-1 w-full" name="category">
                                <option value="" selected disabled hidden>-- Choose category --</option>
                                @foreach($categories as $category)
                                    <option
                                        @if($category->name == old('category'))
                                        selected
                                        @endif
                                        value="{{ $category->name }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mt-4">
                            <x-label for="amount_to_be_raised" :value="__('Minimal Amount To Collect')" />
                            <x-input id="amount_to_be_raised" class="block mt-1 w-full" type="number" name="amount_to_be_raised" :value="old('amount_to_be_raised')" />
                        </div>

                        <div class="mt-4">
                            <x-label for="stop_date" :value="__('Ends before')" />
                            <x-input id="stop_date" class="block mt-1 w-full" type="date" name="stop_date" :value="old('stop_date')" />
                        </div>

                        <div class="mt-4">
                            <x-label for="start_date" :value="__('Starts before')" />
                            <x-input id="start_date" class="block mt-1 w-full" type="date" name="start_date" :value="old('start_date')" />
                        </div>

                        <div class="flex items-center justify-end mt-4">

                            <x-button class="ml-4" type="Submit" value="FilterSubmit" name="filter">
                                {{ __('Filter') }}
                            </x-button>

                            <x-button class="ml-4" type="Submit" value="all" name="filter">
                                {{ __('Show All') }}
                            </x-button>
                        </div>
                    </form>
                    <div class="flex items-center justify-end mt-4 px-4 pb-5">
                        <form method="get" action="{{ route('fundraisers.create') }}">
                            <x-button class="ml-4">
                                {{ __('Create new...') }}
                            </x-button>
                        </form>
                    </div>
                @if( count($fundraisers) < 1 )
                    <p class="p-6">No fundraisers available.</p>
                @else
                    <h3 class="font-semibold text-xl text-gray-800 leading-tight">
                        {{ __('Sort:') }}
                    </h3>
                <div class="pt-8">
                    <form method="get" action="{{ route('fundraisers.index') }}">
                        <x-button class="ml-4" type="Submit" value="amount" name="submit">
                            {{ __('Amount ↓') }}
                        </x-button>
                        <x-button class="ml-4" type="Submit" value="amount2" name="submit">
                            {{ __('Amount ↑') }}
                        </x-button>
                        <x-button class="ml-4" type="Submit" value="date1" name="submit">
                            {{ __('End Date ↑') }}
                        </x-button>
                        <x-button class="ml-4" type="Submit" value="date2" name="submit">
                            {{ __('End Date ↓') }}
                        </x-button>
                    </form>

                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                        <tr>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Title
                            </th>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Amount
                            </th>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Ends at
                            </th>
                        </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">
                        @foreach($fundraisers as $fundraiser)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <a href="{{ route('fundraisers.show', $fundraiser) }}" class="text-indigo-600
                                    hover:text-indigo-900">{{ $fundraiser->title }}</a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm text-gray-900">{{ $fundraiser->amount_raised }} /
                                        {{ $fundraiser->amount_to_be_raised }}</div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    @if($fundraiser->stop_date < \Carbon\Carbon::now()->toDateTimeString())
                                        <div class="text-sm text-red-600">Closed</div>
                                    @else
                                        <div class="text-sm text-gray-900">{{ $fundraiser->stop_date }}</div>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @endif
                </div>
                <div>
                    {{ $paged->links() }}
                </div>
           </div>
        </div>
    </div>
    </div>
</x-app-layout>

Projekt/project/resources/views/fundraisers/show.blade.php
<?php
use \App\Models\User;
?>
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Viewing a fundraiser') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                <div class="bg-black shadow overflow-hidden sm:rounded-lg">
                    <div class="px-4 py-5 sm:px-6">
                        <h3 class="text-lg leading-6 font-medium text-gray-900">
                            <div style="text-align: center;">{{ $fundraiser->title }}</div>
                        </h3>
                    </div>
                    <div class="border-t border-gray-200">
                        <dl>
                            @if($is_closed)
                            <div class="px-4 py-5 sm:px-6 sm:gap-4" style="background-color: indianred">
                                This fundraiser has ended and further donations are not allowed.
                            </div>
                            @endif
                            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    Created by
                                </dt>
                                @if( !isset($fundraiser->user) )
                                    User has deleted their's account.
                                @elseif(Auth::id() == $fundraiser->user->id)
                                    <a style="color: {{User::findOrFail($fundraiser->user_id)->isSpecial()}}" href="{{ route('dashboard')}}" class="text-indigo-600
                                    hover:text-indigo-900"><x-markdown>{{ $fundraiser->user->name }}</x-markdown></a>
                                @else
                                <a style="color: {{User::findOrFail($fundraiser->user_id)->isSpecial()}}" href="{{ route('users.show', $fundraiser->user) }}" class="text-indigo-600
                                    hover:text-indigo-900"><x-markdown>{{ $fundraiser->user->name }}</x-markdown></a>
                                @endif
                            </div>
                            <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    Category
                                </dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    {{ $fundraiser->category->name }}
                                </dd>
                            </div>
                            <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    Amount
                                </dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    {{ $fundraiser->amount_raised }} / {{ $fundraiser->amount_to_be_raised }}
                                </dd>
                            </div>
                            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    Date
                                </dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    Start: {{ $fundraiser->created_at }}
                                    <br>
                                    End: {{ $fundraiser->stop_date }}
                                </dd>
                            </div>
                            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    Description
                                </dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    <x-markdown>
                                        {{ $fundraiser->description }}
                                    </x-markdown>
                                </dd>
                            </div>
                            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    Latest donations
                                </dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    <x-markdown>
                                        @foreach($latest_5_donations as $donation)
                                            <a href="{{ route('fundraisers.donations.show', [$fundraiser, $donation]) }}"
                                               class="text-indigo-600 hover:text-indigo-900">{{$donation->amount}}- {{$donation->description}}</a>
                                            <br>
                                        @endforeach
                                    </x-markdown>
                                </dd>
                            </div>
                            @if( isset($fundraiser->user) && Auth::id() == $fundraiser->user->id && !$is_closed)
                            <div class="bg-white px-4 pb-5 flex items-center justify-end mt-4">

                                <form method="get" action="{{ route('fundraisers.edit', $fundraiser) }}">
                                    <x-button class="ml-4">
                                        {{ __('Edit') }}
                                    </x-button>
                                </form>

                                <form method="post" action="{{ route('fundraisers.destroy', $fundraiser) }}">

                                    @csrf
                                    @method("DELETE")

                                    <x-button class="ml-4">
                                        {{ __('Delete') }}
                                    </x-button>
                                </form>
                            </div>
                            @endif
                            <div class="flex items-center justify-end mt-4 px-4 pb-5">
                                @if(!$is_closed)
                                <form method="get" action="{{ route('fundraisers.donations.create', $fundraiser) }}">
                                    <x-button class="ml-4">
                                        {{ __('Make a donation') }}
                                    </x-button>
                                </form>
                                @endif
                                <form method="get" action="{{ route('fundraisers.donations.index', $fundraiser) }}">
                                    <x-button class="ml-4">
                                        {{ __('See all donations for this fundraiser') }}
                                    </x-button>
                                </form>
                            </div>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>