Projekt/project/routes/web.php
<?php

use App\Models\Donation;
use App\Models\Fundraiser;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|s
*/

Route::get('/', function () {
    $best_3_users = array_slice(User::scopeRanking(Donation::all()), 0, 3);
    $latest_3_donations = Donation::all()->sortByDesc('created_at')->take(3);
    return view('Toss_a_coin', ['latest_3_donations' => $latest_3_donations, 'best_3_users' => $best_3_users])
        ->withFundraisers(Fundraiser::orderByDesc('created_at')->get()->take(3))
        ->withDonations(Donation::all());
})->name('home');

Route::get('/dashboard', function () {
    $user_donations = Donation::all()->where('user_id', '=', auth()->user()->id)->where('is_anonymous', '=', '0');
    $user_anonymous_donations = Donation::all()->where('user_id', '=', auth()->user()->id)->where('is_anonymous', '=', '1');
    $user_fundraisers = Fundraiser::all()->where('user_id', '=', auth()->user()->id);
    $sum_donations = Donation::all()->where('user_id', '=', auth()->user()->id)->sum('amount');

    return view('dashboard', ["user_donations" => $user_donations, "user_fundraisers" => $user_fundraisers,
        "user_anonymous_donations" =>$user_anonymous_donations, "sum_donations" => $sum_donations])
        ->withFundraisers(Fundraiser::all())
        ->withDonations(Donation::all());
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('fundraisers', \App\Http\Controllers\FundraiserController::class);
Route::resource('fundraisers.donations', \App\Http\Controllers\FundraiserDonationController::class);
Route::resource('users', \App\Http\Controllers\Auth\RegisteredUserController::class);

Projekt/project/app/Models/Donation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Donation extends Model
{
    use HasFactory;

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function fundraiser(){
        return $this->belongsTo(Fundraiser::class);
    }
}

Projekt/project/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

Projekt/project/resources/views/donations/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Making a donation') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="post" action="{{ route('fundraisers.donations.store', $fundraiser) }}">

                        @csrf

                        <div class="mt-4">
                            <x-label for="title" :value="__('Amount')" />
                            <x-input id="amount" class="block mt-1 w-full" type="text" name="amount" :value="old('amount')" />
                        </div>

                        <div class="mt-4">
                            <x-label for="title" :value="__('Description')" />
                            <x-input id="description" class="block mt-1 w-full" type="text" name="description" :value="old('description')" />
                        </div>

                        <div class="mt-4">
                            <x-label for="category" :value="__('Do you want to stay anonymoys?')" />
                            <select id="is_anonymous" class="block mt-1 w-full" name="is_anonymous">
                                <option    @if(1 == old('is_anonymous'))
                                           selected
                                           @endif
                                    value="1">Anonymous donation</option>
                                <option    @if(0 == old('is_anonymous'))
                                           selected
                                           @endif
                                    value="0">Show my username</option>
                            </select>
                        </div>

                        <div class="flex items-center justify-end mt-4">

                            <x-button class="ml-4">
                                {{ __('Make a donation') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

Projekt/project/resources/views/donations/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Editing a donation') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="post" action="{{ route('fundraisers.donations.update', [$fundraiser, $donation]) }}">
                    Unfortunately the amount you donated can not be changed. Feel free to change the other details of donation.
                        @csrf
                        @method("PUT")

                        <div class="mt-4">
                            <x-label for="description" :value="__('Description')" />
                            <x-input id="description" class="block mt-1 w-full" type="text" name="description"
                                     :value="$donation->description" />
                        </div>

                        <div class="mt-4">
                            <x-label for="category" :value="__('Do you want to stay anonymoys?')" />
                            <select id="is_anonymous" class="block mt-1 w-full" name="is_anonymous">
                                <option    @if(1 == $donation->is_anonymous)
                                           selected
                                           @endif
                                           value="1">Anonymous donation</option>
                                <option    @if(0 == $donation->is_anonymous)
                                           selected
                                           @endif
                                           value="0">Show my username</option>
                            </select>
                        </div>

                        <div class="flex items-center justify-end mt-4">

                            <x-button class="ml-4">
                                {{ __('Update') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

Projekt/project/resources/views/donations/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('List of donations') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <br class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                @if($fundraiser->donations->isEmpty())
                    <p class="p-6">No donation has been made for this fundraiser.</p>
                @else
                    @foreach($fundraiser->donations as $donation)
                        <a href="{{ route('fundraisers.donations.show', [$fundraiser, $donation]) }}"
                           class="text-indigo-600 hover:text-indigo-900">{{$donation->amount}}- {{$donation->description}}</a>
                        <br>
                    @endforeach
                @endif
        </div>
        </div>
    </div>
</x-app-layout>

Projekt/project/resources/views/donations/show.blade.php
<?php
use Illuminate\Support\Facades\Auth;
use \App\Models\User;
?>
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Viewing a donation') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                <div class="bg-white shadow overflow-hidden sm:rounded-lg">
                    <div class="px-4 py-5 sm:px-6">
                        <h3 class="text-lg leading-6 font-medium text-gray-900">
                          <div style="text-align: center;">{{ $donation->amount }}</div>
                        </h3>
                    </div>
                    <div class="border-t border-gray-200">
                        <dl>
                            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    <br>Donated fundraiser
                                </dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                        <a style="color: black" href="{{ route('fundraisers.show', $donation->fundraiser) }}" class="text-indigo-600
                                    hover:text-indigo-800"><x-markdown>{{ $donation->fundraiser->title }}</x-markdown></a>
                                </dd>
                            </div>
                            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    <br>Description
                                </dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    <x-markdown>
                                        {{ $donation->description }}
                                    </x-markdown>
                                </dd>
                            </div>
                            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    Donated by
                                </dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    @if( !isset($donation->user) )
                                        User has deleted their's account.
                                    @elseif($donation->is_anonymous == 1)
                                            Anonymous donation
                                    @elseif(Auth::id() == $donation->user_id)
                                        <a style="color: {{User::findOrFail($donation->user_id)->isSpecial()}}" href="{{ route('dashboard') }}" class="text-indigo-600
                                    hover:text-indigo-900"><x-markdown>{{ $donation->user->name }}</x-markdown></a>
                                    @else
                                        <a style="color: {{User::findOrFail($donation->user_id)->isSpecial()}}" href="{{ route('users.show', $donation->user) }}" class="text-indigo-600
                                    hover:text-indigo-900"><x-markdown>{{ $donation->user->name }}</x-markdown></a>
                                    @endif
                                </dd>
                            </div>

                            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    Donated at
                                </dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                        {{ $donation->created_at }}
                                </dd>
                            </div>
                            @if( isset($donation->user) && Auth::id() == $donation->user->id)
                            <div class="bg-white px-4 pb-5 flex items-center justify-end mt-4">

                                <form method="get" action="{{ route('fundraisers.donations.edit', [$fundraiser, $donation]) }}">
                                    <x-button class="ml-4">
                                        {{ __('Edit') }}
                                    </x-button>
                                </form>
                            </div>
                            @endif
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>