Projekt/project/routes/web.php
<?php

use App\Models\Donation;
use App\Models\Fundraiser;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|s
*/

Route::get('/', function () {
    $best_3_users = array_slice(User::scopeRanking(Donation::all()), 0, 3);
    $latest_3_donations = Donation::all()->sortByDesc('created_at')->take(3);
    return view('Toss_a_coin', ['latest_3_donations' => $latest_3_donations, 'best_3_users' => $best_3_users])
        ->withFundraisers(Fundraiser::orderByDesc('created_at')->get()->take(3))
        ->withDonations(Donation::all());
})->name('home');

Route::get('/dashboard', function () {
    $user_donations = Donation::all()->where('user_id', '=', auth()->user()->id)->where('is_anonymous', '=', '0');
    $user_anonymous_donations = Donation::all()->where('user_id', '=', auth()->user()->id)->where('is_anonymous', '=', '1');
    $user_fundraisers = Fundraiser::all()->where('user_id', '=', auth()->user()->id);
    $sum_donations = Donation::all()->where('user_id', '=', auth()->user()->id)->sum('amount');

    return view('dashboard', ["user_donations" => $user_donations, "user_fundraisers" => $user_fundraisers,
        "user_anonymous_donations" =>$user_anonymous_donations, "sum_donations" => $sum_donations])
        ->withFundraisers(Fundraiser::all())
        ->withDonations(Donation::all());
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('fundraisers', \App\Http\Controllers\FundraiserController::class);
Route::resource('fundraisers.donations', \App\Http\Controllers\FundraiserDonationController::class);
Route::resource('users', \App\Http\Controllers\Auth\RegisteredUserController::class);

Projekt/project/app/Models/User.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
        'deleted_at',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function donations(){
        return $this->hasMany(Donation::class);
    }

    public function fundraisers(){
        return $this->hasMany(Fundraiser::class);
    }

    public function scopeSumOfDonations($query){
        return $query->where('is_anonymous', '=', '0')->where('user_id', '=', $this->id)->sum('amount');
    }

    public static function scopeRanking(){
        $records = DB::table('donations')->where('is_anonymous', '=', '0')->join('users', 'donations.user_id', '=', 'users.id')->whereNull('deleted_at')
            ->groupBy('id')->get(['users.id', DB::raw('sum(donations.amount) as total')])->sortByDesc('total');
        $ranking = [];
        foreach($records as $record){
            $username = DB::table('users')->whereNull('deleted_at')->where('id', '=', $record->id)->value('name');
            $ranking[] = [$username, $record->total, $record->id];
        }
        return $ranking;
    }

    public function isSpecial(){
        if($this->scopeSumOfDonations(DB::table('donations')->where('is_anonymous', '=', '0')->where('created_at', '>', Carbon::now()->subDays(7))) > 500) {
        return "orange";
        }
        else{
        return "blue";
        }
    }
}

Projekt/project/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

Projekt/project/resources/views/users/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Editing your account') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    <form method="post" action="{{ route('users.update', $user) }}">
                        @csrf
                        @method("PUT")

                        <div class="mt-4">
                            <x-label for="name" :value="__('Name')" />
                            <x-input id="name" class="block mt-1 w-full" type="text" name="name"
                                     :value="old('name') ?? auth()->user()->name" />
                        </div>

                        <div class="mt-4">
                            <x-label for="email" :value="__('Email')" />
                            <x-input id="email" class="block mt-1 w-full" type="text" name="email"
                                     :value="old('email') ?? auth()->user()->email" />
                        </div>

                        <div class="mt-4">
                            <x-label for="password" :value="__('Password')" />

                            <x-input id="password" class="block mt-1 w-full"
                                     type="password"
                                     name="password"
                                     autocomplete="current-password"
                            />
                        </div>

                        <div class="flex items-center justify-end mt-4">

                            <x-button class="ml-4">
                                {{ __('Update') }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

Projekt/project/resources/views/users/index.blade.php
<?php
use App\Models\User;
?>
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Here you can see ranking of our users, who decided to support fundraisers!') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                @if($users->isEmpty())
                    <p class="p-6">No users in database.</p>
                @else
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Name</span>
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Sum of donations</span>
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Details</span>
                            </th>
                        </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">
                        @foreach(User::scopeRanking() as $user)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div style="color: {{User::findOrFail($user[2])->isSpecial()}}" class="text-sm text-500">{{ $user[0] }}</div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm text-gray-500">{{ $user[1] }}</div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <form method="get" action=" @if( isset($_SESSION['logged_user_id']) && $user[2] == $_SESSION['logged_user_id'] ) {{ route('dashboard', $user[2]) }} @else {{ route('users.show', $user[2]) }} @endif">
                                        <x-button class="ml-4">
                                            {{ __('View ') }} {{$user[0]}}'s {{__('profile')}}
                                        </x-button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @endif

            </div>
        </div>
    </div>
</x-app-layout>

Projekt/project/resources/views/users/show.blade.php
<?php
use App\Models\User;
?>
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ $user->name }}{{ __('\'s account')}}

        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                <divfundraisers class="bg-white shadow overflow-hidden sm:rounded-lg">
                    <div class="px-4 py-5 sm:px-6">
                        <h3 style="color:{{$user->isSpecial()}}"class="text-lg leading-6 font-medium text-900">
                            {{ $user->name }}
                        </h3>
                    </div>
                    <div class="border-t border-gray-200">
                        <dl>
                            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    e-mail:
                                </dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    {{$user->email}}
                                </dd>
                            </div>
                            <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    created fundraisers:
                                </dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    @foreach($user_fundraisers as $fundraiser)
                                            <a href="{{ route('fundraisers.show', $fundraiser) }}">{{$fundraiser->title}}</a>
                                            <br>
                                    @endforeach

                                    @if($user_fundraisers->isEmpty())
                                        none
                                    @endif
                                </dd>
                            </div>
                            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    Donations:
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    @foreach($user_donations as $donation)
                                            <a href="{{ route('fundraisers.donations.show', [$donation->fundraiser, $donation]) }}">{{$donation->amount}}</a>
                                            <br>
                                    @endforeach
                                    @if($user_donations->isEmpty())
                                         none
                                    @endif
                                </dd>
                            </div>
                            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                    Sum of donations:
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                    {{ $user->scopeSumOfDonations($donations) }}
                                </dd>
                            </div>
                        </dl>
                    </div>
                </divfundraisers>
            </div>
        </div>
    </div>
</x-app-layout>
</dt>